<form id="login" class="form-signin" action="<?php echo $this->basePath().'/login'; ?>" method="post">
    <input type="hidden" name="_token" value="PHI2GWUEvkR6pSnqsSD2TsCBMp0X6UbEEcqxB33x">
    <div class="form-group">
        <img class="img-sally-center" src="<?php echo $this->basePath().'/res/img/clips-n-girl-200x200.jpg'?>" alt="eCLIPS" width="150" height="150">
    </div>
    <div class="form-group">
        <input id="name" type="text" placeholder="E-mail" name="email" value="">
    </div>
    <div class="form-group">
        <input id="password" type="password" placeholder="Password" name="password" value="">
    </div>
    <a href="<?php echo $this->basePath().'/password/reset'; ?>">Forgot password?</a>
    <button id="login" type="submit">
        <span class="glyphicon glyphicon-paperclip" title="CLiPs Logo"></span>
        <?php echo $this->translate('Login') ?>
    </button>
    <button id="register" type="button">
        <a href="<?php echo $this->basePath().'/register'; ?>" class="">
        <span class="glyphicon glyphicon-education" title="CLiPs Logo"></span>
        <?php echo $this->translate('Register') ?>
        </a>
    </button>
</form>