<?php
if(isset($account) && !empty($account) && is_array($account)) {
    $account = $account[0];
}
?>
<div class="container">
    <div class="row">
        <div class="col-sm-24">
            <p>&nbsp;</p>
        </div>
        <div class="col-sm-24">
            <form id="login" class="form-signin" action="<?php echo  $this->url('logout'); ?>" method="post">
                <div class="form-group">
                    <img class="img-sally-center" src="<?php echo $this->basePath().'/res/img/clips-n-girl-200x200.jpg'?>" alt="eCLIPS" width="150" height="150">
                </div>
                <div class="form-group">
                    Welcome <?php echo $account->getUsername(); ?>
                </div>
                <button id="logout" type="submit">
                    <span class="glyphicon glyphicon-paperclip" title="CLiPs Logo"></span>
                    <?php echo $this->translate('Logout') ?>
                </button>
                <button id="profile" type="button">
                    <a href="<?php echo $this->basePath().'/profile'; ?>" class="">
                        <span class="glyphicon glyphicon-education" title="CLiPs Logo"></span>
                        <?php echo $this->translate('Profile') ?>
                    </a>
                </button>
            </form>
        </div>
    </div>
</div>