<?php
$wpformid = 3;
$wpvars   = [
    'method' => 'post',
    'action' => 'https://weberstudioblog.wordpress.com/contact/#contact-form-'.$wpformid,
    'contact-form-id' => $wpformid,
];
?>
<form action='<?php echo $wpvars['method'] ;?>' method='<?php echo $wpvars['action'] ;?>' class='contact-form commentsblock'>
    <div>
        <label for='g<?php echo $wpvars['contact-form-id'] ;?>-name' class='grunion-field-label name'>Name<span>(required)</span></label>
        <input type='text' name='g<?php echo $wpvars['contact-form-id'] ;?>-name' id='g<?php echo $wpvars['contact-form-id'] ;?>-name' value='weberstudioblog' class='name'  required aria-required='true'/>
    </div>

    <div>
        <label for='g<?php echo $wpvars['contact-form-id'] ;?>-email' class='grunion-field-label email'>Email<span>(required)</span></label>
        <input type='email' name='g<?php echo $wpvars['contact-form-id'] ;?>-email' id='g<?php echo $wpvars['contact-form-id'] ;?>-email' value='black001goat@gmail.com' class='email'  required aria-required='true'/>
    </div>

    <div>
        <label for='g<?php echo $wpvars['contact-form-id'] ;?>-website' class='grunion-field-label url'>Website</label>
        <input type='text' name='g<?php echo $wpvars['contact-form-id'] ;?>-website' id='g<?php echo $wpvars['contact-form-id'] ;?>-website' value='https://weberstudioblog.wordpress.com' class='url'  />
    </div>

    <div>
        <label for='contact-form-comment-g<?php echo $wpvars['contact-form-id'] ;?>-comment' class='grunion-field-label textarea'>Comment<span>(required)</span></label>
        <textarea name='g<?php echo $wpvars['contact-form-id'] ;?>-comment' id='contact-form-comment-g<?php echo $wpvars['contact-form-id'] ;?>-comment' rows='20' class='textarea'  required aria-required='true'></textarea>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-needanoffer' value='Yes' class='checkbox'  />
            : need an offer</label>
        <div class='clear-form'></div>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-needtosellonline' value='Yes' class='checkbox'  />
            : need to sell online</label>
        <div class='clear-form'></div>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-needmyownwebaddress' value='Yes' class='checkbox'  />
            : need my own Web address</label>
        <div class='clear-form'></div>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-needhosting' value='Yes' class='checkbox'  />
            : need hosting</label>
        <div class='clear-form'></div>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-needsearchengineoptimisation' value='Yes' class='checkbox'  />
            : need Search Engine Optimisation</label>
        <div class='clear-form'></div>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-needacustomthemeorplugin' value='Yes' class='checkbox'  />
            : need a Custom Theme or Plugin</label>
        <div class='clear-form'></div>
    </div>
    <div>
        <label class='grunion-field-label checkbox'>
            <input type='checkbox' name='g<?php echo $wpvars['contact-form-id'] ;?>-desireacupofcoffeeortea' value='Yes' class='checkbox'  />
            : desire a cup of coffee or tea.</label>
        <div class='clear-form'></div>
    </div>
    <p class='contact-submit'>
        <input type='submit' value='Submit &#187;' class='pushbutton-wide'/>
        <input type="hidden" id="_wpnonce" name="_wpnonce" value="f171d5baf3" />
        <input type="hidden" name="_wp_http_referer" value="/contact/" />
        <input type='hidden' name='contact-form-id' value='<?php echo $wpvars['contact-form-id'] ;?>' />
        <input type='hidden' name='action' value='grunion-contact-form' />
    </p>
</form>