<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="pragma-directive" content="no-cache" />
    <meta http-equiv="cache-directive" content="no-cache" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">

    <meta name="keywords" content="inspiration, grid, thumbnail, transition, subtle, web design" />
    <meta name="author" content="Ked Weber" />


    <!-- Open Graph -->
    <meta property="og:title" content="WEBerStudio.net: eCLIPS ~ Early Childhood Learning Interactive Profile System" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="https://avatars3.githubusercontent.com/u/11974342?v=3&s=400" />
    <meta property="og:url" content="http://kedweber.github.io/zend2-skeleton-add-flesh" />
    <meta property="og:description" content="eCLIPS is helps teachers collectively produce portfolios and evaluations for their student's parental guardians and lesson plans." />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="WEBerStudio.net: eCLIPS ~ Early Childhood Learning Interactive Profile System" />
    <meta name="twitter:url" content="http://kedweber.github.io/zend2-skeleton-add-flesh" />
    <meta name="twitter:description" content="eCLIPS is helps teachers collectively produce portfolios and evaluations for their student's parental guardians and lesson plans." />
    <meta name="twitter:image" content="https://avatars3.githubusercontent.com/u/11974342?v=3&s=400" />

    <!-- Favicons: apple-touch-icon-180x180.png and favicon.ico are both copied to the root directory
    to avoid extra 404 errors in server logs. In addition manifest.json & browserconfig.xml -->
    <link rel="apple-touch-icon" sizes="180x180" href="/res/img/favicons/apple-touch-icon-180x180.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/res/img/favicons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/res/img/favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/res/img/favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/res/img/favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/res/img/favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/res/img/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/res/img/favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="57x57" href="/res/img/favicons/apple-touch-icon-57x57.png">
    <link rel="icon" type="image/png" href="/res/img/favicons/favicon-194x194.png" sizes="194x194">
    <link rel="icon" type="image/png" href="/res/img/favicons/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/res/img/favicons/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/res/img/favicons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/res/img/favicons/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <meta name="apple-mobile-web-app-title" content="KJV Reader">
    <meta name="application-name" content="KJV Reader">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="msapplication-TileImage" content="res/img/favicons/mstile-150x150.png">
    <meta name="msapplication-config" content="./browserconfig.xml">
    <meta name="theme-color" content="#555555">
    <link rel="shortcut icon" href="favicon.ico">

    <title>eCLIPS ~ Early Childhood Learning Interactive Profile System</title>
    <!-- KILL ME -->
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/res/img/favicons/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/res/css/style.css')
        ->prependStylesheet($this->basePath() . '/res/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/res/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . 'res/js/bootstrap.min.js')
        ->prependFile($this->basePath() . 'res/js/jquery.min.js')
        ->prependFile($this->basePath() . 'res/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . 'res/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
    <!--/ KILL ME -->
</head>