<nav class="navbar navbar-green navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>" title="eChildren's Learning Interactive Profile System">
                <span class="glyphicon glyphicon-paperclip" title="CLiPs Logo"></span>
                &nbsp;eCLIPS
            </a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Page 1</a></li>
            <li><a href="#">Page 2</a></li>
            <li><a href="#">Page 3</a></li>
        </ul>
        <button type="button" class="nav navbar-nav navbar-toggle" data-toggle="collapse" data-target=".not-set">
            <span class="glyphicon glyphicon-menu-down"></span>
            <span class="glyphicon glyphicon-menu-down"></span>
            <span class="glyphicon glyphicon-menu-down"></span>
        </button>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
        <div class="collapse navbar-collapse nav-styrene-box">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?php echo $this->url('admin') ?>">
                        <?php echo $this->translate('Reports') ?>
                        <span class="glyphicon glyphicon-hand-down"></span>
                    </a>
                </li>
                <li><span class="glyphicon glyphicon-bell">Notifications</span></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="nav-buffer"></div>