<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>" title="eChildren's Learning Interactive Profile System">
                <span class="glyphicon glyphicon-paperclip" title="CLiPs Logo"></span>&nbsp;eCLIPS
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate('Home') ?></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="nav-buffer"></div>