
<hr/>
<div class="container">
<?php
$f = $this->form;
$f->prepare();
echo $this->form()->openTag($f); ?>
<?php //echo $this->formCollection($this->form); ?>
<?php


//$f->setAttribute('action', $this->url('admin'));
//
echo $this->partial("clips/partials/sections/section-form-edit", array(
    'fieldSetz' => $this->form
));
?>
<?php echo $this->form()->closeTag(); ?>


    <div class="row">
        <div class="col-24 list-group">
    <?php
//var_dump($this->sections); die();
    foreach($this->sections as $section): ?>
        <?php echo $this->partial("clips/partials/sections/section-list-item", array(
            "section" => $section,
            "basepath" => $this->url('admin')
        )); ?>
    <?php endforeach; ?>
        </div>
    </div>
</div>
