<hr/>
<div class="container">
    <div class="row">
        <div class="col-24">Form:</div>
        <div class="col-24">
<?php
echo $this->form()->openTag($this->form);
//formatted form elements
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
?>
        </div>
    </div>

    <div class="row">
        <div class="col-24">List</div>
        <div class="col-24 list-group">
    <?php foreach($this->sections as $section): ?>
        <?php echo $this->partial("clips/partials/sections/section-list-item", array(
            "section" => $section,
            "basepath" => $this->url('admin')
        )); ?>
    <?php endforeach; ?>
        </div>
    </div>
</div>