<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-xs-24 col-md-12 pull-right">
                <span>
                    <?php echo $this->partial("clips/partials/access/login", array()); ?>
                </span>
            </div>
            <div class="col-xs-24 col-md-12">
                <h2>Early Childhood Learning Interactive Profile System</h2>
                <p>
                    Let CLIPS assist you in completing your student's profiles. Save time while effectively providing the parental
                    guardians the feedback they want and need.
                </p>

                <h3>Why eCLIPS?</h3>
                <p>
                    Teachers are charged with carrying the most precious burden of shaping the future on an astoundingly low
                    budget. Among the many daily tasks an important and personal assessment of the child's development is to be
                    consolidated into a profile. The primary purpose of the profile is to inform the parents of their child's
                    developmental strengths and weaknesses.
                </p>
                <p>
                    When reviewing a child, within the scaffolding of national standards, often teachers find themselves at an
                    impasse. There are a number of factors (areas of observation) that need to be considered based on the child's age.
                </p>
                <p>
                    <strong>CLIPS</strong> will offer an outline of considerations that should be covered, while affording the
                    opportunity to add and customize additional areas of observations. As a teacher selects the level of
                    development for a particular student, a list of applicable general statements will be offered, with an
                    online reference to specialized terminology. The generated statements will be general and are only meant to
                    serve as an aid; a skeleton frame work, which the teacher can then edit to a specific child. Similar to
                    sitting in a think-tank bouncing ideas within a group of related professionals, CLIPS should serve only to
                    assist and stimulate the considerations of the teacher writing the portfolios. Of course in the process of
                    communicating to student's parents, one will wish to find balance between educational jargon and the local
                    vernacular.
                </p>
                <p>
                    Every profile requires adding objects (work samples and observation records) to indicate work done in
                    real-life situations with authentic problem solving. CLIPS will need to allow for inclusion of such custom
                    objects.
                </p>

            </div>

        </div>
    </div>

</div>